import { Open_Sans } from "next/font/google";

import "./globals.scss";
import Navbar from "@/components/organisms/navbar";
import Footer from "@/components/organisms/footer";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
