import { Open_Sans } from "next/font/google";

import "./globals.scss";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

setInterval(() => {
  localStorage.clear(); 
}, 12 * 60 * 60 * 1000);

//ortak layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
